version: "3.4"

services:
  demo_app:
    image: unleash/demo_app
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile.app
    command: sh -c "npx prisma migrate dev --skip-generate --name 'init' && node server.js"
    environment:
      NODE_ENV: production
      UNLEASH_SERVER_API_URL: "https://us.app.unleash-hosted.com/ushosted/api/"
      UNLEASH_SERVER_API_TOKEN: ""
      UNLEASH_FRONTEND_API_URL: "https://us.app.unleash-hosted.com/ushosted/api/frontend"
      UNLEASH_FRONTEND_API_TOKEN: ""
      DATABASE_URL: "postgresql://postgres:example@db:5432/mydb?schema=public"
      JWT_SECRET: "a bunch of silly stuff"
    ports:
      - 3000:3000

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
