version: "3.4"

services:
  demo_app:
    image: unleash/demo_app
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile.app
    command: sh -c "npx prisma migrate deploy --schema ./prisma/schema.prisma && node server.js"
    environment:
      DATABASE_URL: "postgresql://postgres:example@db:5432/mydb?schema=public"
      JWT_SECRET: "a bunch of silly stuff"
      NEXT_PUBLIC_API_URL: "http://localhost:3000"
      NODE_ENV: production
      UNLEASH_FRONTEND_API_TOKEN: "_CHANGE_ME_"
      UNLEASH_FRONTEND_API_URL: "https://us.app.unleash-hosted.com/ushosted/api/frontend"
      UNLEASH_SERVER_API_TOKEN: "_CHANGE_ME_"
      UNLEASH_SERVER_API_URL: "https://us.app.unleash-hosted.com/ushosted/api/"
    ports:
      - 3000:3000

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
